[aws]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✖](bold red)"

[cmd_duration]
min_time = 15_000
style = "italic yellow"

[directory]
style = "blue"
truncation_length = 5
truncate_to_repo = true

[env_var]
variable = "AWSUME_PROFILE"
symbol = ""
style = "italic yellow"

[git_branch]
format = "on [$branch]($style) "
style = "bright-black italic"
truncation_symbol = "…"

[git_state]
style = "italic yellow"

[git_status]
style = "bright-black"
stashed = ""

[hostname]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true

[terraform]
disabled = true

[username]
disabled = true
