" Colors
syntax enable                             " enable syntax processing

" UI Config
set number                                " print line number before each line
set showcmd                               " show (partial) command in bottom bar
set wildmenu                              " enable command-line completion
set lazyredraw                            " do not redraw during non-typed commands
set showmatch                             " briefly jump to matching [{()}]
set matchtime=1                           " tenth of second to show matching [{()}]
set t_Co=256                              " number of colors

" Spaces & Tabs
set tabstop=2                             " number of spaces that \t counts for
set expandtab                             " use spaces to insert a tab
set listchars=trail:∙,tab:>―              " characters to use in list mode (whitespace:char)
set list                                  " enable list mode
set autoindent                            " copy indent from current line when starting a new line

" Highlight current line and column
set cursorline                            " highlight screen line of the cursor
hi cursorline cterm=none term=none        " disable underlining
hi CursorLine ctermbg=015                 " bg colour
set cursorcolumn                          " highlight screen column of the cursor

" Misc
set backspace=indent,eol,start            " allow backspacing over everything
