" Colors
syntax enable                             " enable syntax processing

" Spaces & Tabs
set tabstop=2                             " number of visual spaces per TAB
set softtabstop=2                         " number of spaces in tab when editing
set expandtab                             " tabs are spaces

" UI Config
set number                                " show line numbers
set showcmd                               " show command in bottom bar
set wildmenu                              " visual autocomplete for command menu
set lazyredraw                            " redraw only when we need to.
set showmatch                             " highlight matching [{()}]

" Highlight current line
set cursorline                            " enable cursorline
hi cursorline cterm=none term=none        " disable underlining
highlight CursorLine ctermbg=LightYellow  " set bg colour

" Misc
set backspace=indent,eol,start            " allow backspace over everything
