# GENERAL
fpath=( "$HOME/.zsh/.zfunctions" $fpath )
export EDITOR='vim'
export LESS=" -R "
export LANG=en_US.UTF-8
export PATH="$HOME/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
export TERM="xterm-256color"

# BREW
[ -d "/home/linuxbrew" ] && export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
[ -d "/Users/sdan/work/homebrew" ] && export PATH="/Users/sdan/work/homebrew/bin:$PATH"

# FZF
export FZF_DEFAULT_OPTS="--height 50% --min-height 30 --border --ansi --color light"

# GO
export GOPATH=$HOME/work/go
export PATH=$GOPATH/bin:$PATH

# HOMEBREW
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha

# NODE
export PATH="/usr/local/opt/node@14/bin:$PATH"

# PYTHON
hash pyenv 2> /dev/null && eval "$(pyenv init -)"
source "$HOME/.poetry/env"

# RUBY
hash rbenv 2> /dev/null && eval "$(rbenv init -)"
