# GENERAL
fpath=( "$HOME/.zsh/.zfunctions" $fpath )
export EDITOR='vim'
export LESS=" -R "
export LANG=en_US.UTF-8
export PATH="$HOME/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
export TERM="xterm-256color"

# BREW
[ -d "/opt/homebrew/bin" ] && export PATH="/opt/homebrew/bin:$PATH"
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha
export HOMEBREW_USE_INTERNAL_API=true

# FZF
export FZF_DEFAULT_OPTS="--height 50% --min-height 30 --border --ansi --color light"

# GO
export GOPATH=$HOME/work/go
export PATH=$GOPATH/bin:$PATH

# GOOGLE CLOUD SDK
if [ -f "$HOME/.google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/.google-cloud-sdk/path.zsh.inc"; fi
if [ -f "$HOME/.google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/.google-cloud-sdk/completion.zsh.inc"; fi

# NODE
export PATH="/usr/local/bin/node:$PATH"

# PIPX
export PATH="$HOME/.local/bin:$PATH"

# PYTHON
hash pyenv 2> /dev/null && eval "$(pyenv init -)"
if [ -f "$HOME/.poetry/env" ]; then source "$HOME/.poetry/env"; fi

# RUBY
hash rbenv 2> /dev/null && eval "$(rbenv init -)"

# SUBLIME TEXT
export PATH="/Applications/Sublime Text.app/Contents/SharedSupport/bin:$PATH"

# VSCODE
export PATH="$HOME/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
