#!/usr/bin/env zsh

# HELPER FUNCTIONS
function _has {
  hash "${1}" 2> /dev/null
}

function _source_if_exists {
  [ -f "${1}" ] && source "${1}" "${2}"
}

# SETUP
_source_if_exists "$HOME/.zsh_aliases"                       # aliases
_source_if_exists "$HOME/.zshenv"                            # env
_source_if_exists "$HOME/.zsh_functions"                     # functions
_source_if_exists "$HOME/.zsh_conf"                          # configuration and plugins
_has brew \
  && _source_if_exists "$(brew --prefix)/etc/profile.d/z.sh" # z

# THEME: pure
autoload -U promptinit; promptinit
PURE_GIT_DOWN_ARROW="↓"
PURE_GIT_UP_ARROW="↑"
PURE_PROMPT_SYMBOL='❱'
prompt pure

